site_name: Elna Rust Bootcamp
site_description: This page is used for the ELNA Rust bootcamp
site_url: https://elna-ai.github.com/bootcamp

docs_dir: src

theme:
  name: dracula
  font:
    text: Roboto
    code: 'Open Sans'
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - search.suggest
  
markdown_extensions:
  - toc:
      permalink: false
