site_name: Elna Rust Bootcamp
site_description: This page is used for the ELNA Rust bootcamp
site_url: https://elna-ai.github.com/bootcamp
repo_name: https://github.com/elna-ai/bootcamp
repo_url: https://github.com/elna-ai/bootcamp
edit_uri: "https://github.com/elna-ai/bootcamp"

docs_dir: src

theme:
  name: dracula
  font:
    text: Roboto
    code: 'Open Sans'
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  
markdown_extensions:
  - toc:
      permalink: false
